# Generated by Django 5.2.7 on 2025-11-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_articles', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0.0)),
                ('top_keywords', models.JSONField(blank=True, default=dict)),
                ('sector_counts', models.JSONField(blank=True, default=dict)),
                ('country_counts', models.JSONField(blank=True, default=dict)),
                ('sentiment_distribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField()),
                ('url', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('impact_score', models.IntegerField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_newsar_publish_db2481_idx'), models.Index(fields=['sentiment_score'], name='news_newsar_sentime_6a17fd_idx'), models.Index(fields=['impact_score'], name='news_newsar_impact__fe842e_idx')],
            },
        ),
    ]
