# Generated by Django 5.1 on 2025-11-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='market_mood',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
