# Generated by Django 5.1 on 2025-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_dailysummary_market_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='title_ko',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
