# Generated by Django 5.1 on 2025-11-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_title_ko'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='mood_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
