# Generated by Django 5.1 on 2025-11-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_dailysummary_mood_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='market_change_pct',
            field=models.FloatField(default=0.0),
        ),
    ]
