# Generated by Django 5.1 on 2025-11-29 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, verbose_name='Ticker')),
                ('buy_date', models.DateField(verbose_name='Buy Date')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Buy Price')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Invested Amount')),
                ('sell_date', models.DateField(blank=True, null=True, verbose_name='Sell Date')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Sell Price')),
                ('profit_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit %')),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Profit Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade Record',
                'verbose_name_plural': 'Trade Records',
                'ordering': ['-buy_date'],
            },
        ),
    ]
