# Generated by Django 5.1 on 2025-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_tradetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetransaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SPLIT', 'Stock Split')], max_length=10),
        ),
    ]
