# Generated by Django 5.1 on 2025-12-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_tradetransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='AI Analysis'),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='strategy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Strategy'),
        ),
    ]
