# Generated by Django 5.2.7 on 2025-12-30 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('kakao_refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('kakao_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('kakao_nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kakao_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Kakao Profile',
                'verbose_name_plural': 'User Kakao Profiles',
                'db_table': 'accounts_userprofile',
            },
        ),
    ]
