# Generated by Django 5.2.7 on 2025-11-17 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['symbol']},
        ),
        migrations.AddField(
            model_name='ticker',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='prev_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='vol_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sector',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='universe_keys',
            field=models.CharField(blank=True, help_text='S&P 500, Nasdaq, Russell 2000 등 소속 유니버스', max_length=255, null=True),
        ),
    ]
