# Generated by Django 5.2.7 on 2025-11-17 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0002_alter_ticker_options_ticker_close_ticker_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['market', 'rank', 'symbol']},
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='change_pct',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='close',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='prev_volume',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='universe_keys',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='vol_change_pct',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='volume',
        ),
        migrations.AddField(
            model_name='ticker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='market',
            field=models.CharField(default='NO', help_text='SP500 / NASDAQ100 / RUSSELL2000 등', max_length=32),
        ),
        migrations.AddField(
            model_name='ticker',
            name='rank',
            field=models.PositiveIntegerField(default=0, help_text='Universe 내 순위 (1,2,3...)'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, default='NO', max_length=128),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(blank=True, default='NO', max_length=128),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sector',
            field=models.CharField(blank=True, default='NO', max_length=128),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
