# Generated by Django 5.2.7 on 2025-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0003_alter_ticker_options_remove_ticker_change_pct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['symbol']},
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='rank',
        ),
        migrations.AddField(
            model_name='ticker',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='percent_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='weight',
            field=models.FloatField(blank=True, help_text='Index weight (%)', null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market',
            field=models.CharField(blank=True, help_text='쉼표로 구분된 인덱스: sp500,nasdaq100,russell2000', max_length=64),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
