# Generated by Django 5.2.7 on 2025-11-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0004_alter_ticker_options_remove_ticker_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
