# Generated by Django 5.2.7 on 2025-11-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0005_alter_ticker_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
