# Generated by Django 5.2.7 on 2025-11-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0006_alter_ticker_name_alter_ticker_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
