# Generated by Django 5.2.7 on 2025-11-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0007_alter_ticker_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={},
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='change',
            new_name='change_amount',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='percent_change',
            new_name='change_percent',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='price',
            new_name='last_price',
        ),
        migrations.AddField(
            model_name='ticker',
            name='prev_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
