# Generated by Django 5.2.7 on 2025-11-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0008_alter_ticker_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='is_active',
        ),
    ]
