# Generated by Django 5.2.7 on 2025-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0009_remove_ticker_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='market_cap',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
