# Generated by Django 5.2.7 on 2025-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0010_ticker_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='debt_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
