# Generated by Django 5.1 on 2025-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0012_fundamentaldata_pricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='change_amount',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='change_percent',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='debt_equity',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='market',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='pe_ratio',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='prev_volume',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='weight',
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='debt_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='market',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='change_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='change_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
