# Generated by Django 5.1 on 2025-12-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0013_remove_ticker_change_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={},
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='adj_close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['symbol', 'date'], name='updatedata__symbol__81e18c_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['date'], name='updatedata__date_99ac13_idx'),
        ),
    ]
