# Generated by Django 5.1 on 2025-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0014_cronjob_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
