# Generated by Django 5.1 on 2025-12-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0015_pricehistory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
