# Generated by Django 5.1 on 2025-12-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0016_ticker_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='prev_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='prev_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IntradayCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_candles', to='updatedata.ticker')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='updatedata__symbol__a14636_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
