# Generated by Django 5.1 on 2025-12-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0017_ticker_change_pct_ticker_prev_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
