# Generated by Django 5.1 on 2025-12-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0018_ticker_industry_ticker_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='change_pct',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='prev_close',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='prev_volume',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='volume_change_pct',
        ),
    ]
