# Generated by Django 5.1 on 2025-12-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0019_remove_ticker_change_pct_remove_ticker_last_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='debt_equity',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='market',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='roe',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='weight',
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='enterprise_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='pb_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='trailing_peg_1y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentaldata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fundamentaldata',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
