# Generated by Django 5.1 on 2025-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0020_remove_fundamentaldata_debt_equity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='adj_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='adj_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='adj_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='adj_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='div_cash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='split_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='adj_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
