# Generated by Django 5.1 on 2025-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0021_alter_pricehistory_options_pricehistory_adj_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='market',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
