# Generated by Django 5.1 on 2025-12-06 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0022_ticker_market'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntradayCandle',
        ),
    ]
