# Generated by Django 5.1 on 2025-12-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0023_delete_intradaycandle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='trailing_peg_1y',
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='forward_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='peg_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='ps_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
