# Generated by Django 5.1 on 2025-12-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0024_remove_fundamentaldata_trailing_peg_1y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentaldata',
            name='book_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='debt_to_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='earnings_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='fifty_two_week_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='fifty_two_week_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='free_cash_flow',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='net_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='operating_margins',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='profit_margins',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='recommendation_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='return_on_assets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='return_on_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='revenue_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='target_mean_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='total_cash',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='total_debt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='total_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
