# Generated by Django 5.2.7 on 2025-12-07 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0025_fundamentaldata_book_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='book_value',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='debt_to_equity',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='earnings_growth',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='fifty_two_week_high',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='fifty_two_week_low',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='forward_pe',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='free_cash_flow',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='net_income',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='operating_margins',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='profit_margins',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='ps_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='recommendation_mean',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='return_on_assets',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='return_on_equity',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='revenue_growth',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='target_mean_price',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='total_cash',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='total_debt',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='total_revenue',
        ),
    ]
