# Generated by Django 5.2.7 on 2025-12-07 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0027_alter_fundamentaldata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_prices', to='updatedata.ticker')),
            ],
            options={
                'ordering': ['datetime'],
                'indexes': [models.Index(fields=['symbol', 'datetime'], name='updatedata__symbol__35b8dc_idx')],
                'unique_together': {('symbol', 'datetime')},
            },
        ),
    ]
