# Generated by Django 5.2.7 on 2025-12-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0028_intradayprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntradayPrice',
        ),
    ]
