# Generated by Django 5.1 on 2025-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0029_delete_intradayprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='dividend_rate',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='earnings_growth',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='fifty_two_week_high',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='fifty_two_week_low',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='float_shares',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='forward_pe',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='operating_margin',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='payout_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='peg_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='price_to_book',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='price_to_sales',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='profit_margin',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='recommendation_mean',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='revenue_growth',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='shares_outstanding',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='target_high_price',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='target_low_price',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='target_mean_price',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='total_cash',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='total_debt',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='trailing_pe',
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='book_value_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='earnings_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='eps_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='free_cash_flow_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='interest_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='pb_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='ps_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='revenue_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
