# Generated by Django 5.1 on 2025-12-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0030_remove_fundamentaldata_beta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('adj_open', models.FloatField(blank=True, null=True)),
                ('adj_high', models.FloatField(blank=True, null=True)),
                ('adj_low', models.FloatField(blank=True, null=True)),
                ('adj_close', models.FloatField(blank=True, null=True)),
                ('adj_volume', models.BigIntegerField(blank=True, null=True)),
                ('div_cash', models.FloatField(blank=True, null=True)),
                ('split_factor', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_price_history', to='updatedata.ticker')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='updatedata__symbol__700ddc_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
