# Generated by Django 5.1 on 2025-12-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0031_backuppricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='debt_to_equity',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='interest_coverage',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='ps_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='revenue_per_share',
        ),
    ]
