# Generated by Django 5.1 on 2025-12-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0032_remove_fundamentaldata_debt_to_equity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='current_ratio',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='earnings_yield',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='enterprise_value',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='free_cash_flow_yield',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='return_on_assets',
        ),
        migrations.RemoveField(
            model_name='fundamentaldata',
            name='return_on_equity',
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='average_inventory_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='average_payables_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='average_receivables_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='capex_to_depreciation_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='capex_to_operating_cash_flow_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='capex_to_revenue_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='cash_conversion_cycle_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='current_ratio_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='days_of_inventory_outstanding_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='days_of_payables_outstanding_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='days_of_sales_outstanding_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='earnings_yield_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='enterprise_value_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='ev_to_ebitda_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='ev_to_free_cash_flow_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='ev_to_operating_cash_flow_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='ev_to_sales_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='free_cash_flow_to_equity_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='free_cash_flow_to_firm_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='free_cash_flow_yield_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='graham_net_net_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='graham_number_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='income_quality_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='intangibles_to_total_assets_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='interest_burden_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='invested_capital_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='net_current_asset_value_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='net_debt_to_ebitda_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='operating_cycle_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='operating_return_on_assets_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='research_and_developement_to_revenue_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='return_on_assets_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='return_on_capital_employed_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='return_on_equity_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='return_on_invested_capital_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='return_on_tangible_assets_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='sales_general_and_administrative_to_revenue_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='stock_based_compensation_to_revenue_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='tangible_asset_value_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='tax_burden_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='working_capital_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
