# Generated by Django 5.1 on 2025-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0033_remove_fundamentaldata_current_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ceo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='dcf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='full_time_employees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ipo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='is_actively_trading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='is_etf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticker',
            name='last_dividend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
