# Generated by Django 5.1 on 2025-12-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0034_ticker_beta_ticker_ceo_ticker_dcf_ticker_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='volume_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
