# Generated by Django 5.1 on 2025-12-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0035_pricehistory_volume_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
