# Generated by Django 5.1 on 2025-12-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0036_cronjob_is_running_cronjob_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='price_target_consensus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='target_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='target_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='target_median',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
