# Generated by Django 5.1 on 2025-12-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0037_ticker_price_target_consensus_ticker_target_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='stoch_long_trend',
            field=models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down'), ('Neutral', 'Neutral')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='stoch_mid_trend',
            field=models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down'), ('Neutral', 'Neutral')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='vestiq_scan',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
