
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
import os
from django.conf import settings

# Register Korean Font (NanumGothic)
FONT_PATH = os.path.join(settings.BASE_DIR, "static", "fonts", "NanumGothic.ttf")
if os.path.exists(FONT_PATH):
    pdfmetrics.registerFont(TTFont("NanumGothic", FONT_PATH))
    KOREAN_FONT = "NanumGothic"
else:
    KOREAN_FONT = "Helvetica" # Fallback

def draw_wrapped_text(c, text, x, y, max_width, font_name, font_size, line_height=None):
    if line_height is None:
        line_height = font_size * 1.4
    
    c.setFont(font_name, font_size)
    words = text.split()
    lines = []
    current_line = []
    
    # Simple word wrapping (imperfect for Korean but functional)
    # For Korean, character-based wrapping is better, but let's stick to simple logic for now
    # or use reportlab's Paragraph if needed. Here we do simple char splitting for long strings.
    
    # Improved wrapping for mixed content
    import textwrap
    lines = textwrap.wrap(text, width=int(max_width / (font_size * 0.6))) # Approx char width

    for line in lines:
        c.drawString(x, y, line)
        y -= line_height
    
    return y

def generate_earnings_pdf(buffer, symbol, data):
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # Header
    c.setFont(KOREAN_FONT, 24)
    c.drawString(50, height - 50, f"Earnings Report: {symbol}")
    
    c.setFont(KOREAN_FONT, 10)
    c.drawString(50, height - 70, "Generated by Vestiq AI Advisor")
    
    y = height - 100
    
    # Executive Summary
    c.setFont(KOREAN_FONT, 16)
    c.setFillColor(colors.darkblue)
    c.drawString(50, y, "Executive Summary")
    y -= 30
    c.setFillColor(colors.black)
    y = draw_wrapped_text(c, data.get("summary", ""), 50, y, width - 100, KOREAN_FONT, 10)
    y -= 20
    
    # Sentiment
    c.setFont(KOREAN_FONT, 12)
    sentiment = data.get("sentiment", "Neutral")
    c.drawString(50, y, f"AI Sentiment: {sentiment}")
    y -= 30
    
    # Key Takeaways
    c.setFont(KOREAN_FONT, 16)
    c.setFillColor(colors.darkgreen)
    c.drawString(50, y, "Key Takeaways")
    y -= 30
    c.setFillColor(colors.black)
    for point in data.get("key_takeaways", []):
        y = draw_wrapped_text(c, f"- {point}", 50, y, width - 100, KOREAN_FONT, 10)
    y -= 20
    
    # Financial Highlights
    if data.get("financial_table"):
        c.setFont(KOREAN_FONT, 16)
        c.setFillColor(colors.darkorange)
        c.drawString(50, y, "Key Financials")
        y -= 30
        c.setFillColor(colors.black)
        ft = data.get("financial_table", {})
        info_str = f"Revenue: {ft.get('Revenue')} | EPS: {ft.get('EPS')} | PER: {ft.get('PER')} | PBR: {ft.get('PBR')}"
        y = draw_wrapped_text(c, info_str, 50, y, width - 100, KOREAN_FONT, 10)
        y -= 20

    # Gemini Prediction
    if data.get("gemini_prediction"):
        c.setFont(KOREAN_FONT, 16)
        c.setFillColor(colors.purple)
        c.drawString(50, y, "Gemini Prediction (6M)")
        y -= 30
        c.setFillColor(colors.black)
        pred = data.get("gemini_prediction", {})
        c.drawString(50, y, f"Target: {pred.get('price_6m')} (Premium: {pred.get('premium')})")
        y -= 20
        y = draw_wrapped_text(c, f"Rationale: {pred.get('rationale')}", 50, y, width - 100, KOREAN_FONT, 10)
        y -= 20

    # Analyst Targets
    if data.get("institutional_targets"):
        c.setFont(KOREAN_FONT, 16)
        c.setFillColor(colors.firebrick)
        c.drawString(50, y, "Analyst Targets")
        y -= 30
        c.setFillColor(colors.black)
        targets = data.get("institutional_targets", {})
        c.drawString(50, y, f"Low: ${targets.get('low')} | Mean: ${targets.get('mean')} | High: ${targets.get('high')}")
        y -= 20
        y = draw_wrapped_text(c, targets.get("summary", ""), 50, y, width - 100, KOREAN_FONT, 10)
        y -= 20

    # CEO Quote
    if data.get("ceo_quote"):
        y -= 10
        c.setFont(KOREAN_FONT, 12)
        c.setFillColor(colors.gray)
        y = draw_wrapped_text(c, f"\"{data.get('ceo_quote')}\"", 70, y, width - 140, KOREAN_FONT, 10)
        c.drawString(width - 150, y, "- Management")

    c.save()
