# Generated by Django 5.2.7 on 2025-11-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
