# Generated by Django 5.2.7 on 2025-11-07 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0002_delete_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('universe_sz', models.IntegerField(default=0)),
                ('notes', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ScanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('close', models.FloatField()),
                ('bb_bbl', models.FloatField()),
                ('rsi', models.FloatField()),
                ('trigger', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='scanner.scanbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'trigger', 'symbol'], name='scanner_sca_batch_i_3a624d_idx')],
            },
        ),
    ]
