# Generated by Django 5.2.7 on 2025-11-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scanrow',
            name='scanner_sca_batch_i_3a624d_idx',
        ),
    ]
