# Generated by Django 5.2.7 on 2025-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_remove_scanrow_scanner_sca_batch_i_3a624d_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrow',
            name='bb_bbl',
        ),
        migrations.RemoveField(
            model_name='scanrow',
            name='rsi',
        ),
        migrations.AddField(
            model_name='scanrow',
            name='prev_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='vol_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scanrow',
            index=models.Index(fields=['batch', 'trigger', 'symbol'], name='scanner_sca_batch_i_3a624d_idx'),
        ),
    ]
