# Generated by Django 5.2.7 on 2025-11-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_remove_scanrow_bb_bbl_remove_scanrow_rsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrow',
            name='price_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
