# Generated by Django 5.2.7 on 2025-11-11 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_scanrow_price_change_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='scanner.scanbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'batch'], name='scanner_air_symbol_38bf6d_idx')],
            },
        ),
    ]
