# Generated by Django 5.2.7 on 2025-11-12 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_aireport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aireport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='aireport',
            name='scanner_air_symbol_38bf6d_idx',
        ),
        migrations.AddField(
            model_name='scanrow',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scanbatch'),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
