# Generated by Django 5.2.7 on 2025-11-13 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_alter_aireport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireport',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scanbatch'),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='scanner.scanbatch'),
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'ordering': ['symbol', 'date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
