# Generated by Django 5.2.7 on 2025-11-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_alter_aireport_batch_alter_scanrow_batch_dailyprice'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scanrow',
            name='scanner_sca_batch_i_3a624d_idx',
        ),
        migrations.AddField(
            model_name='scanrow',
            name='f_momentum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='f_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='f_trend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='f_volatility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='f_volume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='industry',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='symbol',
            field=models.CharField(max_length=16),
        ),
        migrations.AddIndex(
            model_name='scanrow',
            index=models.Index(fields=['batch', 'symbol'], name='scanner_sca_batch_i_6e3ef7_idx'),
        ),
    ]
