# Generated by Django 5.2.7 on 2025-11-15 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_remove_scanrow_scanner_sca_batch_i_3a624d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanbatch',
            old_name='universe_sz',
            new_name='scanned_count',
        ),
        migrations.RemoveField(
            model_name='scanbatch',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='scanbatch',
            name='notes',
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='avg_price_change',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='avg_vol_change',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='triggered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
