# Generated by Django 5.2.7 on 2025-11-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_rename_universe_sz_scanbatch_scanned_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='symbol',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='symbol',
            field=models.CharField(max_length=255),
        ),
    ]
