# Generated by Django 5.2.7 on 2025-11-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_alter_dailyprice_symbol_alter_scanrow_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='symbol',
            field=models.CharField(max_length=16),
        ),
    ]
