# Generated by Django 5.2.7 on 2025-11-18 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_alter_dailyprice_symbol_alter_scanrow_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aireport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailyprice',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='scanrow',
            name='scanner_sca_batch_i_6e3ef7_idx',
        ),
        migrations.RemoveField(
            model_name='scanbatch',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='aireport',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scanbatch'),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='avg_price_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='avg_vol_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrow',
            name='trigger',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='dailyprice',
            index=models.Index(fields=['symbol', 'date'], name='scanner_dai_symbol_b022d4_idx'),
        ),
    ]
