# Generated by Django 5.2.7 on 2025-11-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_alter_aireport_options_alter_dailyprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrow',
            name='f_value',
            field=models.BooleanField(default=False),
        ),
    ]
