# Generated by Django 5.1 on 2025-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0015_scanrow_f_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrow',
            name='f_oversold',
            field=models.BooleanField(default=False),
        ),
    ]
