# Generated by Django 5.1 on 2025-11-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_scanrow_f_oversold'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrow',
            name='f_lux',
            field=models.BooleanField(default=False),
        ),
    ]
