# Generated by Django 5.1 on 2025-11-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_scanrow_f_lux'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrow',
            name='f_gap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='f_squeeze',
            field=models.BooleanField(default=False),
        ),
    ]
