# Generated by Django 5.1 on 2025-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_scanrow_f_gap_scanrow_f_squeeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrow',
            name='vcs',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
