# Generated by Django 5.1 on 2025-12-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0019_scanrow_vcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VestiqPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('price', models.FloatField()),
                ('found_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chart_data', models.JSONField(default=list)),
            ],
        ),
    ]
