# Generated by Django 5.1 on 2025-12-06 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0020_vestiqpick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VestiqPick',
        ),
    ]
