# Generated by Django 5.2.7 on 2025-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0021_delete_vestiqpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrow',
            name='ma20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='ma60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='rvol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrow',
            name='score_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
