# Generated by Django 5.2.7 on 2025-12-08 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0022_scanrow_ma20_scanrow_ma60_scanrow_rsi_scanrow_rvol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('symbol', models.CharField(max_length=20)),
                ('strategy', models.CharField(default='Prime', max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
                'unique_together': {('date', 'symbol')},
            },
        ),
    ]
