# Generated by Django 5.1 on 2025-12-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0023_dailypick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypick',
            name='strategy',
            field=models.CharField(default='Prime', max_length=255),
        ),
    ]
