# Generated by Django 5.1 on 2025-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sector', models.CharField(max_length=100)),
                ('change_percent', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('leaders_data', models.JSONField(blank=True, default=list)),
                ('gainers_data', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'rank'],
                'unique_together': {('date', 'sector')},
            },
        ),
    ]
