# Generated by Django 5.1 on 2025-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_sectorperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorperformance',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
