# Generated by Django 5.1 on 2025-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_sectorperformance_pe_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('eps_actual', models.FloatField(blank=True, null=True)),
                ('eps_estimated', models.FloatField(blank=True, null=True)),
                ('revenue_actual', models.BigIntegerField(blank=True, null=True)),
                ('revenue_estimated', models.BigIntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'symbol'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
