# Generated by Django 5.2.7 on 2025-11-19 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.BigIntegerField(help_text='총 투자 가능 금액 ($)')),
                ('risk_tolerance', models.CharField(choices=[('low', 'Low (안정형 - 원금 보존 중시)'), ('medium', 'Medium (중립형 - 밸런스 중시)'), ('high', 'High (공격형 - 고수익 추구)')], default='medium', max_length=10)),
                ('duration_months', models.IntegerField(default=12, help_text='투자 기간 (개월 단위)')),
                ('target_return', models.FloatField(blank=True, help_text='목표 수익률 (%)', null=True)),
                ('monthly_contribution', models.BigIntegerField(default=0, help_text='월 추가 납입 가능 금액 ($)')),
                ('investment_goal', models.CharField(choices=[('retirement', '노후 자금 마련'), ('house', '주택 구입 자금'), ('wealth', '자산 증식 (부자 되기)'), ('short_term', '단기 목돈 마련 (여행/결혼 등)')], default='wealth', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_json', models.JSONField(help_text='자산 배분 비율 (JSON)')),
                ('tickers_json', models.JSONField(help_text='추천 종목 리스트 (JSON)')),
                ('rationale', models.TextField(help_text='AI의 투자 근거 및 조언')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_advisor.investmentprofile')),
            ],
        ),
    ]
