# Generated by Django 5.1 on 2025-11-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('current_price', models.FloatField()),
                ('volume', models.BigIntegerField(null=True)),
                ('price_change_pct', models.FloatField(null=True)),
                ('vol_change_pct', models.FloatField(null=True)),
                ('market_mood', models.CharField(max_length=20)),
                ('market_mood_score', models.IntegerField(null=True)),
                ('recommendation', models.CharField(db_index=True, max_length=10)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('position_size', models.CharField(blank=True, max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('technical_score', models.FloatField(default=0)),
                ('filters_triggered', models.JSONField(default=list)),
                ('risk_reward_ratio', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-date', '-technical_score'],
                'indexes': [models.Index(fields=['date', 'recommendation'], name='ai_advisor__date_500793_idx')],
            },
        ),
    ]
