# Generated by Django 5.1 on 2025-11-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0002_traderecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermPickReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(help_text='Full JSON response from Gemini')),
            ],
        ),
    ]
