# Generated by Django 5.1 on 2025-11-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0003_longtermpickreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermpickreport',
            name='language',
            field=models.CharField(db_index=True, default='ko', max_length=10),
        ),
        migrations.AddField(
            model_name='traderecommendation',
            name='language',
            field=models.CharField(db_index=True, default='ko', max_length=10),
        ),
        migrations.AddIndex(
            model_name='traderecommendation',
            index=models.Index(fields=['date', 'language'], name='ai_advisor__date_1d3746_idx'),
        ),
    ]
