# Generated by Django 5.2.7 on 2025-11-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0004_longtermpickreport_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprofile',
            name='investment_goal',
            field=models.CharField(choices=[('retirement', 'Retirement Fund'), ('house', 'House Purchase'), ('wealth', 'Wealth Accumulation'), ('short_term', 'Short-term Lump Sum (Travel/Wedding)')], default='wealth', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentprofile',
            name='risk_tolerance',
            field=models.CharField(choices=[('low', 'Low (Stable - Principal Protection)'), ('medium', 'Medium (Balanced)'), ('high', 'High (Aggressive - High Return)')], default='medium', max_length=10),
        ),
    ]
