# Generated by Django 5.1 on 2025-11-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0005_alter_investmentprofile_investment_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioreport',
            name='strategy_name',
            field=models.CharField(default='Custom Strategy', help_text='전략 이름', max_length=100),
        ),
    ]
